# Generated by Django 5.0.6 on 2024-06-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_teacher_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='avatar',
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers/'),
        ),
    ]
